### ISSUE TITLE
[Wiki] Provide existing arc for example command `arc get`

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#104]
**Describe the bug**
`arc get -r https://github.com/nfdi4plants/ARC/tree/Example-ARC.git`

**To Reproduce**
1. Go to https://github.com/nfdi4plants/arcCommander/wiki/2.-ARC-initialization
2. Execute above command in local terminal
```
fatal: repository 'https://github.com/nfdi4plants/ARC/tree/Example-ARC.git/' not found
ERROR: Git command could not be run. 
```

**Expected behavior**
Cloning from an actually existing arc.git.

**Comment by Martin-Kuhl** [comment]
Apparently, the URL was incorrect. 
Fixed it in the wiki. Can you please try again with the new line?

**Comment by Brilator** [comment]
Thanks. Works fine. 
Btw. wiki is ahead of release ;), `arc get` is not part of v0.0.4
No pressure.
