### ISSUE TITLE
[BUG] investigation file deviates from ISA

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCCommander#107]
**Describe the bug**
I've spotted two little deviations from the original ISA Model specs in the isa.investigation.xlsx produced by arcCommander. (Possibly also relevant for ISADotNet?): 

1. Study Protocol Parameters Name (lines 74, 75 in investigation.xlsx)

- ARC 
```
Study Protocol Parameters Term Accession Number
Study Protocol Parameters Term Source REF
```

- ISA (https://isa-specs.readthedocs.io/en/latest/isatab.html#study-section)
```
Study Protocol Parameters Name Term Accession Number
Study Protocol Parameters Name Term Source REF	
```

2. PubMed ID (lines 13, 44) 

- ARC
```
Investigation Publication PubMed ID
---
Study Publication PubMed ID
```

- ISA 
```
Investigation PubMed ID
---
Study PubMed ID
```

For 2., the arcCommander version is actually more coherent than the original regarding other `Publication` keys.

**Comment by HLWeil** [comment]
Hey, thanks for pointing this out! 

Regarding `1.`:  This is actually a bit weird if you check the `Protocol` section in the link again.. By their specification, my header without the `Name` is correct (This is what I used as a basis for my implementation). But in the example they provided themselves, the `Name` is included.

Regarding `2`:  This incoherence kind of really annoys me 😄. Maybe we could ask the guys at ISA for their reasoning behind this, and whether this is up for debate? In general getting into contact with them might be beneficial.
Adjusting this in `ISADotNet` is of course the quick alternative

**Comment by HLWeil** [comment]
See https://github.com/nfdi4plants/ARC-specification/blob/main/ARC%20specification.md
