### ISSUE TITLE
Unify application naming

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arcCommander#12]
The executable is named `ArcCommander.exe`, just as the respective project (ArcCommander.fsproj). 
However, the Argu setup implies that the main command/executable should be `arc` :

```F#
let parser = ArgumentParser.Create<Arc>(programName = "arc")
```

When the file names should not be touched, the executable name could be changed via MSBuild properties in the fsproj file.

**Comment by HLWeil** [comment]
I removed the manual naming, hopefully removing the confusion. Now it's just good old `ArcCommander.exe`
