### ISSUE TITLE
[BUG] study cannot be deleted

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#121]
**Describe the bug**

```
ERROR: Couldn't delete study file:
  System.IO.DirectoryNotFoundException: Could not find a part of the path ... 
```
**To Reproduce**

within arc root: 

```bash
arc s add -s some_study
arc s remove -s some_study
```

**Comment by Brilator** [comment]
Not sure if fixed in between

**Comment by Brilator** [comment]
Still exists in v3.1. Unregister works though. 

And for assays it's kind of the other way round: 
If you add an assay and specify the study (which did not exist before), 
```
arc a add -s ThisIsMyStudy -a ThisIsMyAssay
```

you cannot delete the assay alone (without specifying the study). 
```
arc a remove -a ThisIsMyAssay
```

Not sure if intended or occurred during re-organisation of studies.

**Comment by omaus** [comment]
> Still exists in v3.1.

Was a bit bigger and also lead to change some functionality. It will be done by the end of today.
