### ISSUE TITLE
[BUG] buggy arc update after upgrade to arc_v1.1

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#124]
**Describe the bug**
`arc update` in this arc https://git.nfdi4plants.org/brilator/samplearc_rnaseq keeps adding (duplicating) the assay "Talinum_RNASeq_minimal" under same study identifier ("Talinum_RNASeq_minimal") to isa.investigation.xlsx. 

Note: This arc wasn't setup freshly, but migrated from version before arcCommander  v0.3.

Can't spot where this comes from 

**To Reproduce**
1. Clone above arc
2. `arc update`
3. see isa.investigation.xlsx growing with duplicated assays

**Comment by HLWeil** [comment]
Hey @Brilator , can you check whether this problem still persists in [0.5.0-preview.1](https://github.com/nfdi4plants/arcCommander/releases/tag/v0.5.0-preview1-fat)?
