### ISSUE TITLE
[Feature Request] warning for long assay / study titles

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#126]
**Is your feature request related to a problem? Please describe.**
Excel bugs with long (>31 characters) sheet names. 

**Describe the solution you'd like**
Just a quick warning to reduce titles to max. 31 chars and preferentially without specials and spaces. 

**Additional context**

Try 

```bash
arc s add -s 'This Is a very long Title that Excel does not like'
```

see Excel error (at least on Mac):

"We found a problem with some content in 'isa.study.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

**Comment by HLWeil** [comment]
Hey @Brilator, good point! Besides this length constraint, also some other constraints like characters that clash with the different OS path names need to be blocked for some arguments. E.g. for windows:
![image](https://user-images.githubusercontent.com/17880410/163354804-74527577-0af8-4757-935f-606cc4beed92.png)

@muehlhaus, @chgarth, @omaus, maybe we could collect similar constraints here in this issue?

**Comment by omaus** [comment]
> Hey @Brilator, good point! Besides this length constraint, also some other constraints like characters that clash with the different OS path names need to be blocked for some arguments. E.g. for windows: ![image](https://user-images.githubusercontent.com/17880410/163354804-74527577-0af8-4757-935f-606cc4beed92.png)
> 
> @muehlhaus, @chgarth, @omaus, maybe we could collect similar constraints here in this issue?

` ` (Space) is difficult on Linux and should be avoided (though it is not forbidden). Maybe replacing with `_` when OS is Linux?  
Only `/` and `NUL` are forbidden in Linux. Don't know for Mac. @Brilator ?
