### ISSUE TITLE
[BUG] issue with old git version (?) 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#128]
**Describe the bug**
Just leaving this issue here reported by a colleague. 

This is probably not intended
```
$ arc init
Start processing command with the arguments:
	Branch:Field ""
	EditorPath:Field ""
	GitLFSByteThreshold:Field ""
	Owner:Field ""
	RepositoryAddress:Field ""
 
Start Arc Init 
ERROR: GIT: error: unknown switch `b' 
```

Although I do note it seems to have setup a directory structure all the same.
It did however lead to issues 
```
ERROR: System.InvalidOperationException: Not a git repository: no .git directory found in the specified directory or any parent directory.
```

down the line (@`arc sync -r ...`); that could in turn be fixed by running `git init`.
Idk, if arc was supposed to call any other parameters when `git init` failed,
something with 'b' perhaps?; but it seems to work for the moment anyway.

**OS and framework information (please complete the following information):**
 - OS: ubuntu
 - OS Version 20.04
- git version 2.25.1

**Comment by HLWeil** [comment]
Oh okay I see, the `-b` flag is used to specify the name of the branch. This flag did unfortunately not yet exist in that [git version](https://git-scm.com/docs/git-init/2.27.0). 
I know that naming the branch is not really a key feature. In most cases `git init` is enough. But also I'm not sure how feasible it is to implement fallback workflows for older git versions, as there are way too many possible complications to catch.

Maybe the `ArcCommander` could check for the installed `git version` and throw a warning when it is below `v2.35.0` which was the current version when most git related features in the ArcCommander were updated?

**Comment by Brilator** [comment]
Good idea in general. 
But it looks like happening on `arc init` only - no branching intended.

**Comment by HLWeil** [comment]
The way I implemented it, `-b` is always used. When you don't specify a branch name yourself, it sets `main` as the branch name. This way I wanted to prevent git from setting `master` as the default branch.

**Comment by Brilator** [comment]
Makes sense, but then maybe implement the two-liner branch+checkout that is compatible with git ≤ v2.35.0

**Comment by HLWeil** [comment]
Yeah that's probably the best solution 👍

**Comment by HLWeil** [comment]
I looked into this and the `-b` flag has already been part of git for the past 2 years. IMO this exceeds the backwards capability that we could and should aim for. So I will close this issue.
