### ISSUE TITLE
[BUG] Access token retrieval does not work

### ISSUE THREAD

**Issue by bvenn** [nfdi4plants/arcCommander#131]
After building the latest developer branch of the arcCommander I tried to execute the following command

`arc remoteaccess accesstoken get -s git.nfdi4plants.org`

I got the following error:
![image](https://user-images.githubusercontent.com/28917670/167572165-01d19d6a-3451-4cc6-bdf3-0b65e6521fb1.png)

URL: https://git.nfdi4plants.org/oauth/authorize?response_type=code&state=qu1YYq-h3GyAoQ6Xv4aWZA&code_challenge=6oUs7Q7Lhs-EB8PttebUPZgt4tWbdwDI7wvE68FFCOE&code_challenge_method=S256&client_id=dataplant-arc-commander&scope=openid%20email%20git-access-token%20git-host&redirect_uri=http%3A%2F%2Flocalhost%3A7890

**OS and framework information (please complete the following information):**
 - OS: Win10
 - OS Version: 10.0.22000

**Comment by HLWeil** [comment]
@j-bauer, do you have an idea what might be the reason for this error? 

For me it works on different machines. @bvenn tried it on Microsoft Edge and Google Chrome and it failed in both cases.

**Comment by j-bauer** [comment]
Checked the settings in GitLab and the client-id is 'arc-commander' and not 'dataplant-arc-commander'. Makes me wonder how it worked for you @HLWeil ?

**Comment by HLWeil** [comment]
Ooof yeah I see the mistake now. Default config is not yet updated on the developer branch..

Thanks for pointing me there 👍

**Comment by HLWeil** [comment]
Should be fixed since `v0.3.2`

27adc34aec45370b1886e1ecc3336c8c729a0ea6
