### ISSUE TITLE
[BUG] OS-specific file linking

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCCommander#133]
**Describe the bug**
Depending on OS (e.g. Win vs. Mac) files are linked differently, e.g.:
- Unix: `mystudy/isa.study.xlsx`
- Win: `mystudy\isa.study.xlsx`

**To Reproduce**
- Add study or assay to an ARC on win or mac

**Comment by HLWeil** [comment]
Related to https://github.com/nfdi4plants/ISADotNet/issues/48

**Comment by HLWeil** [comment]
fixed in #219
