### ISSUE TITLE
[Feature Request] Use custom error messages

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arcCommander#135]
**Is your feature request related to a problem? Please describe.**
Currently, error messages from exceptions seem to be passed directly to stdout. This includes the stack trace.

**Describe the solution you'd like**
Exceptions should be catched by the app and re-formatted, at least for errors where it is possible to know what went wrong. I'd suggest using custom exceptions thrown by the app, which are then matched and used to display more helpful error messages than the stack traces.

For example, ther could be an `UnknownArgumentException` type, and an exception handler function for subcommands:

```fsharp
open System

type ArcCommanderException(code : int, msg : string) =
    inherit Exception(msg)
    member e.Code = code // this means we can further match the error, would also be possible to use a DU here
    new (msg : string) = ArcCommanderException(0, msg)

let exceptionhandler (e: Exception) =
    match e with
    | :? ArcCommanderException as ae -> 
        match ae.Code with 
        | 0 -> "print something for code 0"
        | 1 -> "print something for code 1"
        | _ -> "etc"
    | e -> e.Message
```

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/21338071/168535104-eda03b85-5e07-4380-9e0c-4eac971cfa78.png)

(on another note, it might be good to add `-h` as shorthand flag for `--help`)

**Comment by omaus** [comment]
For normal, we already customized Error Messages due to the logging.  
![image](https://user-images.githubusercontent.com/47781170/168553081-0f95e934-4754-487d-a874-45e864aeeb77.png)  
Your case is a case we missed to catch before the error occurs (i.e. trying to look into a `studies` folder though it might not exist).

Would rather see this as a bug to fix.

> (on another note, it might be good to add -h as shorthand flag for --help)

I agree on that.
