### ISSUE TITLE
[BUG] arc export duplicates assay into new study

### ISSUE THREAD

**Issue by floWetzels** [nfdi4plants/arcCommander#141]
**Describe the bug**
When I run `arc export` on the proteomics samplearc (https://git.nfdi4plants.org/martinkuhl/SampleARC_Proteomics), the output json file contains two studies (see first screenshot):

- A "normal" study `01Minimal` with filename `01Minimal/isa.study.xlsx`
- A study assay with filename `assay1/isa.assay.xlsx`

However, the assay is actually registered in the study, as can be seen with `arc a list` or `arc s list` (see second screenshot). Therefore, there should only be one study containing the only assay. The study `01Minimal` contains `assay1` in the json output, but whithout a process sequence attached, whereas the assay itself (and therefore the second study) does contain the process sequence.

**To Reproduce**
Run `arc export` on the proteomics samplearc (https://git.nfdi4plants.org/martinkuhl/SampleARC_Proteomics).

**Expected behavior**
The output should only contain one assay and one study, with the only assay being part of the only study.

**Screenshots**

![Screenshot from 2022-07-06 14-13-48](https://user-images.githubusercontent.com/36967183/177549243-c6ab8a0c-4d8a-4f94-a4e4-dffe2dca1f54.png)

![Screenshot from 2022-07-06 14-16-14](https://user-images.githubusercontent.com/36967183/177549010-f3e44800-1b7c-41cb-8ca6-6f31c0e09f88.png)

**OS and framework information (please complete the following information):**
 - OS: Ubuntu
 - OS Version 20.04

**Comment by Brilator** [comment]
I think the duplication issue is fixed. However, `arc study list` stills throws the error 
> WARNING: The ARC contains following registered studies that have no associated file: 

check `arc s list` on freshly re-built https://git.nfdi4plants.org/brilator/samplearc_rnaseq
