### ISSUE TITLE
[Feature Request] Include common junk items in standard .gitignore

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander#143]
Some files created by OS specific programs might clutter folders in the `ARC`, adding unnecessary additional overhead to all steps included (Like syncing with the git remote).
Files like this might include the `Desktop.ini`.
 
The `ArcCommander` already has a standard `.gitignore`, that can optionally be created when initializing the `ARC`. Maybe this `.gitignore` might be extended with some additional rules for catching these unwanted files.

@dvs-frbg @muehlhaus @chgarth

**Comment by chgarth** [comment]
Good idea. We can borrow from [this repo](https://github.com/github/gitignore/tree/main/Global), which has ignore rules for macOS, Windows, Linux, and MS Office.
