### ISSUE TITLE
[Bug] `arc sync`

### ISSUE THREAD

**Issue by bvenn** [nfdi4plants/ARCCommander#147]
When working on a feature branch `arc sync` should target that branch rather than trying to push to the main branch. Of course you can specify the branch using `arc sync -b <branchName>` but if you already are on that branch, it should be chosen.

**Additional context**
Current workflow:

```
//changes on branch "myBranch"
//git status validates beeing on "myBranch"
arc sync -m "add xy"
//changes are pushed to main branch
//git status validates beeing on "main"
```

**Comment by omaus** [comment]
Good idea. But maybe this is also up to debate since this is, imo, a matter of habit, too. But in general, I like your idea and would also prefer it to be that way.
@HLWeil what do you think?

**Comment by HLWeil** [comment]
This is actually how it's supposed to work. So I'll mark this issue as a bug instead. Thanks for the heads up, @bvenn
