### ISSUE TITLE
[BUG] inputs in JSON output file are duplicated on occasion

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/arcCommander#153]
**Describe the bug**
When I tried to export the rnaseq sample ARC of Dominik i noticed an issue in the output.json file. In the last study (7th study) in the assays section (in the second process: process 3ASY01_RNASeq_0) the inputs are duplicated (12 inputs instead of 6) and contain factor information from the previous process of the process sequence (2EXT01_RNA_0).

**To Reproduce**
1. Clone the public sample ARC: https://git.nfdi4plants.org/brilator/samplearc_rnaseq
2. execute "arc export -o <output.json>
3. go to line 2012 in the json-formatted output file to get to the inputs section

**Expected behavior**
As there are only 6 lines for the mentioned assay, I also only expected 6 input entries, one for each input source. In the outputs of this process there are only the expected 6 outputs with the factor information from this process (this structure is confusing as well, I opened a second issue for this).

**Screenshots**
![Bildschirmfoto von 2022-10-17 11-39-54](https://user-images.githubusercontent.com/108814050/196145937-8d81d223-649f-4d2a-9a25-3a435bb44d5e.png)

**OS and framework information (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - ARCcommander version: v0.3.2

**Additional context**
Perhaps information is duplicated because in the first process the outputs are "samples" while in the second process the outputs from the first are the new inputs and thus labeled with "source"?

**Comment by HLWeil** [comment]
See answer to #154
