### ISSUE TITLE
Use a dedicated logging library

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arcCommander#16]
It may be beneficial to refactor the prints in the API functions to use a dedicated logger like [NLog](https://nlog-project.org/). Verbosity of commands should then be adaptable via a `verbosity` argument. This has the advantage that we can control both verbosity of console output and get the possibility to save these messages into a log file.

**Comment by omaus** [comment]
> I think this might be closed, @omaus?

Thought it would with merging #88 but it somehow didn't (or I misunderstood a GitHub functionality).
