### ISSUE TITLE
[Feature Request] Add instruction on how to get access token to wiki

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/arcCommander#163]
**Is your feature request related to a problem? Please describe.**
I just wanted to clone an already existing Arc. I promptly found the instruction on how-to proceed in the wiki. However, my access was denied due to the reason that I did not have a valid access token. I think it would be nice to point out how to retrieve one.

**Describe the solution you'd like**
Explain usage of 

`arc remote accesstoken get -s https://git.nfdi4plants.org`

[here](https://github.com/nfdi4plants/arcCommander/wiki/2.-ARC-initialization)

Maybe it would be also nice to rename the section of the wiki into something more descriptive like "Create your own or access existing Arc"

**Comment by andreaschrader** [comment]
You can find a short and detailed version of such a description here: Arc Commander - Authentication Step Fix - detailed version #157. There is a German version followed by the English version below in the first comment.

**Comment by andreaschrader** [comment]
Also, this was added to an FAQ section which is currently under preparation.

**Comment by andreaschrader** [comment]
This issue can be closed.
