### ISSUE TITLE
Only the pointers and not the files are downloaded when using arc sync [BUG]

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/arcCommander#164]
**Describe the bug**
When using arc sync the files in /assays/datasets are not downloaded from the remote repo when and as they were uploaded with git lfs. 

**Additional context**
When working collaboratively this causes issues when using e.g. RStudio with R scripts in Workflows. than, the pionter is loaded and not the file and hence the scripts can not be executed and further developped locally.

git lfs pull solves the problem.

As this might be aprotective behaviour to avoid downloading accidentally very large files, an option for arc sync to allow this or maybe even to pass a list with specific files which should be available locally would be beneficial.

Hope I did not oversee anything covering and pointing the user to this point!

**Comment by HLWeil** [comment]
Hey, so is this behaviour specific to `sync` or also to `get`?

Also did you build the ArcCommander yourself or are you using an available Release? (Asking because in the newest `unreleased changes` I added a `flag` to `arc get`, with which one can choose whether to download `lfs files` or not #158) 

In the repo you try to sync, are the `lfs files` specified online in the `.gitattributes` file?

**Comment by andreaschrader** [comment]
I used arc sync and just tried arc get. This shows the same behaviour. Have to use the token workaround, maybe this matters?

Just changed to 0.3.4 on Mac and followed your instructions  for MacOS in the README. Also had to use the workaround with the token for authentification I noted in the discussions (also for arc get). 

I do not know how to inspect the online .gitattributes file but the local one includes the following: "**/dataset/** filter=lfs diff=lfs merge=lfs -text"

The flag you mention will be nice. I think specifically selecting which lfs files to download would be beneficial in cases of very large or many files.

**Comment by HLWeil** [comment]
This was a bug of version `<=0.3.4`, resulting in missing `.gitattributes` files, which was adressed in version `0.4.0`. Will close this for now. Feel free to reopen if the problem persists.
