### ISSUE TITLE
[BUG] Registered study has no associated file

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/arcCommander#178]
After adding a study via `arc s add `, the ARC Commander prints the warning displayed below after submitting `arc s list`. Interestingly, the warning does not appear when submitting `arc a list`, which results in a correct output of the assay with the associated study.

To reproduce:
1. Add a study to an ARC via `arc s add`.
2. Call all registered studies via `arc s list`.

![image](https://user-images.githubusercontent.com/87656451/214855533-d674742b-608a-4f96-a1ca-d8c87c43c84c.png)

**Comment by omaus** [comment]
Fixed in https://github.com/nfdi4plants/arcIO.NET/commit/e5bbf1903817a47c479328edd9910ef938ef990e
