### ISSUE TITLE
[BUG] arc update not working

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#179]
**Describe the bug**

`arc update` does not sync metadata from study / assay to investigation

**To Reproduce**

```bash
mkdir ~/Desktop/test-arc; cd ~/Desktop/test-arc
arc init
arc i create -i test-inv
arc s add -s test-study
```

```bash
open studies/test-study/isa.study.xlsx
```

- Change some values in the `Study` sheet.
- Save and close all excel workbooks. 

```bash
arc update
```

Observe no change in `isa.investigation.xlsx`

(The file`s "Date modified" changes. But it does not sync the change from study to investigation. )

**OS and framework information (please complete the following information):**
 - OS: maOCS Ventura
 - OS Version 13.2
- arc --version v0.4.0

**Comment by HLWeil** [comment]
Hey @Brilator,

The update functionality in general is really lacking and I'm currently working on this.

**Comment by Brilator** [comment]
`arc update` seems to work in version built from branch arcIONetMigration, dc7f3b759c3cb3c0890194b6c905e9c8cb381de6 


macOS Ventura 13.2
