### ISSUE TITLE
[Feature Request] backward compatibility of "arc export"

### ISSUE THREAD

**Issue by xiaoranzhou** [nfdi4plants/arcCommander#182]
**Is your feature request related to a problem? Please describe.**

The current linux bin of arcCommander [v0.4.0-linux.x64](https://github.com/nfdi4plants/arcCommander/releases/tag/v0.4.0-linux.x64) generate a different and smaller arc.json compared with the [v0.2.1-linux.x64](https://github.com/nfdi4plants/arcCommander/releases/tag/v0.2.1-linux.x64).
The newest is around 9kb while the 0.2.1's arc.json is 199kb

**Describe the solution you'd like**
Is it possible to make the "arc export" backward compatible? For example, add a new command "arc export_1" or something like that, which can generate the old JSON file.

**Describe alternatives you've considered**
I will look deeper into the two files, to see if the information is the same. From a first glance, I can not find the the source file and output related parameters.

**Additional context**
old arc.json: https://raw.githubusercontent.com/nfdi4plants/arc2repo/main/wasm/debug/issue/export.json
new arc.json: https://raw.githubusercontent.com/nfdi4plants/arc2repo/main/wasm/debug/issue/new_export.json

**Comment by xiaoranzhou** [comment]
> Hey Xiaron, in your `new` exported json, the `ProcessSequence` of the `assay` is missing. Could you share a link to the ARC you are trying to export?

Hi Lukas, thanks for your quick reply, sorry I was busy working on a poster. 

I tried to export this repo https://gitlab.nfdi4plants.de/hlweil/samplearc_rnaseq

**Comment by HLWeil** [comment]
Hello again, 

I looked in the repo and now fully understood what you meant with "backward compatability". The problem you mentioned in general was actually as bug, that I fixed in the newest release 0.5.0. 
Unfortunately, I can't guarantee it will also work for the specific ARC you linked here, as it has a deprecated structure. Currently, there are no plans to actively develop the ArcCommander to provide backwards compatability for the few ARCs that were created in this state. 
But the ARC you linked actually was manually updated. It is available here: https://git.nfdi4plants.org/brilator/samplearc_rnaseq

**Comment by xiaoranzhou** [comment]
Hi Lukas,
Thanks a lot for the quick update. I have tried the new "arc export" on the updated repo. It seems working, but the structures of the JSON and the repo both changed a lot. Is there a document describe the changes? For example, there are new "sources" , "sample", and "material" sections, how is it connected to the input and output section in the protocols of old JSON ? I rewrite the converter to adapted the changes that exist in the "sample arc" and "arc.JSON", but I can not predict other possible changes.

**Comment by HLWeil** [comment]
Hey Xiaoran,
in principle, I'm just moving towards more exhaustively filling all fields of the [isa-json specification](https://isa-specs.readthedocs.io/en/latest/isajson.html#investigation-schema-json). What I added in this release are just some top level fields, which group some information from the lower levels (Basically a distinct copying). If you were already using the `inputs` and `outputs` of the `processes` of the `assays` and `studies`, you won't need to adapt to also incorporate this information.

**Comment by xiaoranzhou** [comment]
Thank a lot for the tips and explaination. I will continue to focusing on inputs and outputs of the processes of the assays and studies.
I will close this issue now.
