### ISSUE TITLE
[BUG] inconsistencies on study level

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#184]
**Describe the bug**

`arc update` does not transfer any metadata from isa.study.xlsx:"Study" to isa.investigation. xlsx

Not sure, if simply buggy (see #179) or conceptional / implementation. 

Currently, `arc update` fills the section `STUDY CONTACTS` with `ASSAY PERFORMERS` from isa.assay.xlsx:"Assay".

**Comment by HLWeil** [comment]
Can you check, if this issue persists in 0.5.0?

**Comment by Brilator** [comment]
Checked with v0.0.5. I still find it confusing, that `ASSAY PERFORMERS` become `STUDY CONTACTS`. 
Goes together with #197
