### ISSUE TITLE
[Feature Request] Reduce verbosity of error messages (or add argument for the verbosity level)

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arcCommander#189]
Here is a specific example of output that is way to verbose IMO:

`arc i person add`
- there is no `add` subcommand
- therefore, arccommander tries to find an external executable named `add`
- it does not exist, cli tool exits with error code

the output (currently, all of the trext below is printed on typing `arc i person add`):

- verbosity level: `default`, this is the only default output that should be printed here IMO:
  ![image](https://user-images.githubusercontent.com/21338071/234219105-e070b8db-8ac3-4015-b93d-4124594c8824.png)

  The order seems wrong here though. shouldn't it be:

  ```
  Could not parse given commands.
  ERROR: unrecognized argument: 'add'.
  Try checking if executable with given argument name "arc-i-person-add" exists.
  ERROR: No executable, command or script file with given argument name known.
  ```

- verbosity level: `informational` at best, i would suggest to stop printing full help messages on errors per default:

  ![image](https://user-images.githubusercontent.com/21338071/234219226-30e98da6-f5fb-46f8-995d-3b3e4176533f.png)

- verbosity level: `debug`. This is something an end user should not see per default.
  
  ![image](https://user-images.githubusercontent.com/21338071/234219339-86074fbd-be4a-4bf8-82a9-ca59bf581ca9.png)

**Comment by HLWeil** [comment]
There is a verbosity flag: `--verbosity` (`-v`) you can use. 

With levels from 0 = no info to 2 = full info (standard is 1)

E.g.: `arc -v 0 a add -a abc` will add the assay with no info.

**Comment by HLWeil** [comment]
I will close this issue. Feel free to reopen if this isn't the solution you liked.

**Comment by kMutagene** [comment]
Is the output i posted still the default output? if so, i would not agree this to be closed, as it is still too verbose
