### ISSUE TITLE
[Feature Request] arc init --gitignore should ignore OS-typical files

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#191]
see e.g. https://github.com/nfdi4plants/ARCitect/pull/5#issuecomment-1545394736

**Comment by HLWeil** [comment]
Hey this was already implemented in #168 and is already included in the latest release: https://github.com/nfdi4plants/arcCommander/releases/tag/v0.5.0-preview1-fat

Will close this issue. Feel free to reopen if needed.
