### ISSUE TITLE
[Feature Request] Latest release

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#194]
Would be helpful to have latest releases to all OS' assets tagged as "latest", so that they'd be listed / linkable under https://github.com/nfdi4plants/arcCommander/releases/latest. 

Unfortunately, only one release can be "latest", so no idea for a good solution without confusion.

**Comment by HLWeil** [comment]
Only solution I see would be a FAT release with executables for all OSs. But of course this would quadruple the package size

**Comment by HLWeil** [comment]
As you stated, I don't think there is a solution to this issue. So I'm going to close it.

@Brilator feel free to reopen if needed.
