### ISSUE TITLE
[Feature Request] STUDY PUBLICATIONS section in isa.study.xlsx

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#197]
**Is your feature request related to a problem? Please describe.**

The default "study" sheet was reduced somewhere between arc v0.4 and v0.5. 

Unfortunately, one (IMO important) section was lost during this update: STUDY PUBLICATIONS

STUDY PUBLICATIONS |  
-- | --
Study Publication PubMed ID |  
Study Publication DOI |  
Study Publication Author List |  
Study Publication Title |  
Study Publication Status |  
Study Publication Status Term Accession Number |  
Study Publication Status Term Source REF

**Describe the solution you'd like**
This section is very useful to reference external data and I'd suggest to add it back.

**Comment by HLWeil** [comment]
The section still exists in the isa.investigation.xlsx. IMO, keeping both sections synced causes too much overhead and too many sources for error compared to the added benefits.

**Comment by Brilator** [comment]
Hm, but then why keep the Study sheet anyways? Just for Study Identifier and Study File Name

**Comment by HLWeil** [comment]
https://github.com/nfdi4plants/ARCtrl/issues/167
We are considering moving the study section to the study file altogether. This is not how it's like in ISA-Tab, but it could be a possibility in ISA-XLSX, as we do have sheets. This could be more intuitive for the user to have all information about a given object (e.g. study) in a single file.

What do you think, @Brilator?

**Comment by HLWeil** [comment]
*moving includes removing from investigation file

**Comment by Brilator** [comment]
Makes sense in terms of everything as one package, e.g. if I want to share only one study or assay (folder) rather than the whole ARC. 
Might however come with a bit of (teaching/explaining) overhead, if we deviate from original ISA too much.

**Comment by HLWeil** [comment]
Also at the cost of straying further from standard ISA...
