### ISSUE TITLE
remove files from syncing [Feature Request] 

### ISSUE THREAD

**Issue by eik-dahms** [nfdi4plants/ARCCommander#199]
**Is your feature request related to a problem? Please describe.**
It should be possible to exclude files from syncing out of 3 reasons:

1. copyright issues: files or data, that should not appear publicly in the ARC  because the user has no rights to do so
2. confidential: data, algorithms that are temporarely confidential
3. big files: user does not want to sync big files

**Describe the solution you'd like**
to ignore files:
`arc ignore <files/folders>`
to remove files from ignore list
`arc include <files/folders>`

**Comment by HLWeil** [comment]
For this, the `.gitignore` should be used. Not sure whether it makes sense to also add this functionality into the ArcCommander.

**Comment by HLWeil** [comment]
Will close this as it's very unlikely I will be working on this.
