### ISSUE TITLE
[BUG] statustermaccessionnumber and statustermsourceref exchanged in output

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/arcCommander#203]
Update (2023-08-11): v0.4.0-osx.x64

**Describe the bug**
--statustermaccessionnumber and --statustermsourceref  are exchanged in the isa.investiation file

**To Reproduce**
When passing a command like this:
arc i publication register --doi "10.XYZ" -p "1234" --authorlist "Author1; Author2; Author3" --title "TITLE" --status "xyz" --statustermaccessionnumber "12324" --statustermsourceref "ABC"

The last two arguments are switched in the isa.investigation file.
Next to 
***Investigation Publication Status Term Accession Number***
there is ***ABC***
and next to ***Investigation Publication Status Term Source REF***
there is ***12324***

**Expected behavior**
Next to 
***Investigation Publication Status Term Accession Number***
there is ***12324*** 
and next to ***Investigation Publication Status Term Source REF***
there is ***ABC***

**OS and framework information (please complete the following information):**
 - OS: [macOS]
 - OS Version [Ventura 13.5]

**Comment by HLWeil** [comment]
Hey,

are you using ArcCommander prerelease version 0.5.0?

**Comment by andreaschrader** [comment]
No, iI am using v0.4.0-osx.x64.

**Comment by andreaschrader** [comment]
Installed preview2 of v0.5.0.
Same issue there.
