### ISSUE TITLE
Lower barrier for annotation: e.g. Mandatory investigation identifier

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/arcCommander#205]
Update (2023-08-11): v0.4.0-osx.x64

**Observation:**
In my persecption, filling the investigation metadata can act as a road block especially when filling an ARC for a project in planning or progress.

**Suggestion:** 
Help with some supportive text directly in the dialogue and explicitlely suggest temporary solutions directly in the tool and not in additional support elsewhere to ensure that the users finds a way around the very first road blocks.

**Detailed Explanation/Background:**
When starting to fill the investigation metadata, the first entry is already a block in order to proceed.
It is a mandatory field, the investigation identifier.
In the dialogue and at ISA it says "A identifier or an accession number provided by a repository. This SHOULD be locally unique."

ISA was not designed for ARCs and ARCs might have at least temporarily some differing requirments.

Ideally, users start their ARC when they start with their project and not when they are submitting an investigation eventually. 

**Possible solutions:**
Therefore, a title could be given and a description provided but the study ID which is mandatory is not available yet.
With respect to an ARC, one could think about the ARC itself as a repository maybe, but I do not think this is what is behind the ISA definition and probably not true when the content eventually gets submitted or partially submitted to respective repositories?

The problem I see here is that the fields to be filled in the investigation part, which intuitively a user would start with, are designed for the submission of a project close to the end of one research adat life "circle".
Other very difficult parts are the roles which might change and might be very diffcult to judge on from a student's perspective.

I think it would be good to have a temporary solution until data is submitted to a repository. Using the ARC's name as the investigation identifier could solve this and could also be suggest next to the ISA text in the arcCommander dialogue upon "arc i create" to help the user.
Moreover one could add e.g. for the roles: "If you can define all roles of the contact person for this investiagtion already please fill them in here. If not, please come back to this section later and update it using "arc i person update --role""

**Comment by omaus** [comment]
IDs are not that important from an experimenter's point of view. But they are from a machine's. Allowing for not filling IDs makes it much more difficult to computationally comprehend the relations between different parts of an ARC.
Maybe @HLWeil has another opinion on this but I don't see an easy way to circumvent IDs at the creation of an ARC's high-level element (Investigation, Study, Assay, ...).

Since IDs are not so important for the experimenter, they should not worry about it. They can also choose a rather bland name. For them, Title and Description are (much) more important.

**Comment by andreaschrader** [comment]
Exactly, they should not worry about it, and suggesting to give a nonsense name means a random nonsense name could as well be created. But this is not what I wanted to suggest here and what I think to be the best solution.
I included some comments in this PR for the Knowledge Base (https://github.com/nfdi4plants/nfdi4plants.knowledgebase/pull/224).
However, I would suggest to add a few words in the mentioned dialogue suggesting using e.g. the ARC's name in case the user does not yet have any other ID at hand or in mind.

**Comment by HLWeil** [comment]
`arc investigation create` will be merged into `arc init` (as the specification mandates that a correct arc MUST have an investigation file)

`arc init` will now use the directory name as an identifier if no identifier is given.
