### ISSUE TITLE
[Feature Request]Rename repo/API or tool

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arcCommander#208]
There are imo too many different naming conventions across our repos. However, some patterns have emerged, which i quite like:

- PascalCase for libraries, but with ARC in all caps.
  examples: 
    - [ARCtrl](https://github.com/nfdi4plants/ARCtrl)
    - [ARCTokenization](https://github.com/nfdi4plants/ARCTokenization)
    
 - kebap-case for tools
  examples:
    - [arc-validate](https://github.com/nfdi4plants/arc-validate)
    - [arc-to-invenio](https://github.com/nfdi4plants/arc-to-invenio)
    - [arc-export](https://github.com/nfdi4plants/arc-export)
    - [arc-from-insdc](https://github.com/nfdi4plants/arc-from-insdc)

so my suggestion would be renaming the API from `ArcCommander` to `ARCCommander`, and the tool from `arc` to `arc-commander`. 

If these changes are too big, I think we should at least rename the repo accordingly, since the current name - `arcCommander` - does not follow any pattern mentioned above, but is also differing from the current tool name (`arc`) and API namespace (`ArcCommander`).

**Comment by kMutagene** [comment]
See also https://github.com/nfdi4plants/arc-validate/issues/42

**Comment by HLWeil** [comment]
I agree with renaming the repo to `ARCCommander`. But I think we should stick with the tool name `arc` for ease of use.

**Comment by kMutagene** [comment]
@HLWeil do you intend to publish the API used by the tool as nuget package? If so, i think you should also rename the API namespace. Otherwise it does not really matter.

**Comment by HLWeil** [comment]
Can you specify what you mean with `API`?

**Comment by kMutagene** [comment]
https://github.com/nfdi4plants/arcCommander/tree/developer/src/ArcCommander/APIs

**Comment by kMutagene** [comment]
> ﻿namespace ArcCommander.APIs

**Comment by kMutagene** [comment]
or is that basically obsolete now that ARCtrl exists?

**Comment by omaus** [comment]
> or is that basically obsolete now that ARCtrl exists?

That was the plan (at least to _my_ knowledge).

**Comment by HLWeil** [comment]
Ah I see. Yeah this definitely won't make it into its own nuget package. It will just be a thin layer combining ARCtrl top-level functions.

**Comment by HLWeil** [comment]
Renamed repository to `ARCCommander`
