### ISSUE TITLE
[BUG] arc a remove/delete do not recognize -s as argument

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/arcCommander#210]
**Describe the bug**
When using `arc a remove` or `arc a delete` as currently described in the Knowledgebase the following error occurs:

ERROR: ERROR: unrecognized argument: '-s'.

**To Reproduce**
In the arcCommander:

`arc init`
`arc i create --identifier Test_investigation`
`arc s add -identifier Test_study`
`arc a add -s Test_study -a Test_assay`

So far so good. When using:
`arc a list`
both study seem to have been correctly created.

Start processing parameterless command.

Start Assay List
Study: Test_study
--Assay: Test_assay
Done processing command.

Then when trying to remove the assay again with:

`arc a remove -s Test_study -a Test_assay`

the above mentioned error occurs.

**Expected behavior**
Based on the current documentation, I would expect this to delete and unregister the assay.
I saw that issue #190 requests to remove the studyidentifier argument, which I generally think is a good idea, so I am not sure if this has been already partially implemented. However when using the command without the study identifier, e.g. :

`arc a remove -a Test_assay`

a long error occurs (see in screenshots)

As a workaround one can of course separately delete and unregister the assay. However when using
`arc a delete -s Test_study -a Test_assay`
the studyidentifier argument is again not recognized
Meanwhile
`arc a delete -a Test_assay`
`arc a unregister -s Test_study -a Test_assay`
works

**Additional context**
if `arc a remove` combines `arc a delete` and `arc a unregister` then the error maybe results from them currently being incompatible.

**Screenshots**
![image](https://github.com/nfdi4plants/arcCommander/assets/73993884/cb10b441-feea-403b-a8ac-23c4cac4466b)

**OS and framework information**
 - OS:  Windows 10
 - arcCommander v0.5.0-win.x64

**Comment by HLWeil** [comment]
Seems like there was some mix-up with the argument lists between these different commands. 
Thanks for bringing it up!

**Comment by HLWeil** [comment]
My proposed change would be the following:

Drop the `--studyidentifier` from the `arc assay remove` command.

Instead, the command only takes the assayidentifier, deletes the assay from the ARC and unregisters it from all studies in the ARC.

Does this make sense to you? @micwij

**Comment by micwij** [comment]
> Does this make sense to you? @micwij
Yes this sounds like a great solution!
