### ISSUE TITLE
[BUG] Pipeline failure arc init

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/arcCommander#213]
**Describe the bug**
In the first commit after initializing an ARC a part of the pipeline fails.

**To Reproduce**
1. Create a new ARC in the DataHUB
2. Initializing ARC and connecting to remote repository: `arc init --repositoryaddress https://git.nfdi4plants.org/micwij/arabidopsis-light-dark-gwas.git`
3. Syncing with `arc sync -m "initialized ARC"`
4. As far as I can remember there was not even a direct error and I noticed it only later when I got two e-mails that said:

Arabidopsis light dark GWAS | Auto DevOps pipeline was disabled for Arabidopsis light dark GWAS

and

Arabidopsis light dark GWAS | Failed pipeline for main | c8a70542

I put a screenshot how it looks in the DataHUB. Let me know what else I can provide.

**Screenshots**
![image](https://github.com/nfdi4plants/arcCommander/assets/73993884/0e55c52e-06aa-46bb-925d-bef2c7ec6673)

**OS and framework information (please complete the following information):**
 - OS: Windows 10
 - ARCCommander v0.5.0

**Additional context**
This has happened twice now, since switching to ARCCommander v0.5.0 and I think this error has not occurred before. On the other hand I did these two ARCs at my institute computer and I am not sure, whether I have only used my private computer before.

**Comment by omaus** [comment]
This might be happening due to the metadata retrieval not getting the information as it needs.

@Zerskk

**Comment by Zerskk** [comment]
@micwij 
This error can be ignored for now.
It actually occurs because the metadata could not be retrieved. This is not a disadvantage and in the future this flow will continue. However, we will still optimise the AutoDevOps flow to make it a bit clearer.

**Comment by micwij** [comment]
@Zerskk 
Thanks for the information!
