### ISSUE TITLE
[Feature Request] Labels (comments) for ORCID iDs are currently inconcise.

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/arcCommander#217]
**Is your feature request related to a problem? Please describe.**
Orcid iDs are currently added with inconcise lables:
Comment[\<Investigation Person ORCID>] for the Investigation Contact Person in the isa.investigation file
Comment[\<Investigation Person ORCID>] also for the Study Contact Person in the isa.investigation file
Comment[\<Worksheet>] for the Assay Performers added to the Study Contact Person in the isa.investigation file and within the isa.assay file

**Describe the solution you'd like**
Suggestion:
Comment[\<Investigation Person ORCID>] for the Investigation Contact Person in the isa.investigation file
Comment[\<Study Person ORCID>] for the Study Contact Person in the isa.investigation file and isa.study file
Comment[\<Assay Person ORCID>] for the Assay Performers in the isa.investigation file and isa. assay file (optional also in isa.study file but registered assay's information is currently not updated in there.

 - OS: macOS
 - OS Version Ventura 13.5.1
 - ARC Commander verison: v0.5.0

**Comment by HLWeil** [comment]
This will be auto-fixed with the ARCtrl integration (See my [comment](https://github.com/nfdi4plants/arcCommander/issues/214#issuecomment-1705265881)). If I remember correctly, the ORCID comment string will now always be `ORCID`.
