### ISSUE TITLE
[BUG] arc config set -g -n

### ISSUE THREAD

**Issue by wunderbarr** [nfdi4plants/arcCommander#218]
**Describe the bug**
Follow the command here: https://www.nfdi4plants.de/nfdi4plants.knowledgebase/docs/ArcCommanderManual/arc_config.html

I get the following error info:

```
arc config set -g -n "general.gitname" -v "myname"
Start processing command with the arguments:
	Global:Flag
	Name:Field "general.gitname"
	Value:Field "myname"
ERROR: Name general.gitname does not exist in the config.
```

Similar error also fro the command: `arc config set -g -n "general.gitemail" -v "Email of choice"`

**To Reproduce**
Execute the command: `arc config set -g -n "general.gitname" -v "myname"`

**Expected behavior**
It could work

**Screenshots**

**OS and framework information (please complete the following information):**
 - OS: [Ubuntu]
 - OS Version [22.04]

**Comment by HLWeil** [comment]
Got the same error in windows. Not sure what's the problem though. 

We did some major backend overhaul and it will take some time till those changes and new bugfixes find their way into the ARCommander. Until then, the following command should work

```
arc config setgituser -l -n "yourName" -e "yourEmail"
```

Which has to be done once in every new ARC.

**Comment by HLWeil** [comment]
This is the same error as https://github.com/nfdi4plants/ARCCommander/issues/138. The operation works, even though the logger reports an error.
