### ISSUE TITLE
[BUG]arc init fails creation of git repository

### ISSUE THREAD

**Issue by cmohl2013** [nfdi4plants/arcCommander#224]
**Describe the bug**
I initialize an ARC with `arc init` in a newly created directory.
`arc init` fails to create a git repository.

**To Reproduce**

```
mkdir my_arc
cd my_arc
git --version
git version 2.25.1
git lfs --version
git-lfs/3.4.0 (GitHub; linux amd64; go 1.20.6; git d06d6e9e)
arc init
Start processing command with the arguments:
	Branch:Field ""
	EditorPath:Field ""
	GitLFSByteThreshold:Field ""
	Owner:Field ""
	RepositoryAddress:Field ""
 
Start Arc Init 
ERROR: GIT: error: unknown switch `b' 
GIT: usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>] 
GIT:  
GIT:     --template <template-directory> 
GIT:                           directory from which templates will be used 
GIT:     --bare                create a bare repository 
GIT:     --shared[=<permissions>] 
GIT:                           specify that the git repository is to be shared amongst several users 
GIT:     -q, --quiet           be quiet 
GIT:     --separate-git-dir <gitdir> 
GIT:                           separate git dir from working tree 
GIT:  
Done processing command. 
```

**Expected behavior**
Git repository is created, no error message.

**OS and framework information (please complete the following information):**
 - OS: Ubuntu
 - OS Version 20.04.6 LTS

**Additional context**

- git version 2.25.1
- git-lfs/3.4.0 (GitHub; linux amd64; go 1.20.6; git d06d6e9e)
- arc version v0.5.0

**Comment by HLWeil** [comment]
Hey @cmohl2013, thank you for the feedback!

If I remember correctly, we had similar issues before. This is most definitely a problem of the `git` version. Can you update your git installation and try again?

**Comment by cmohl2013** [comment]
Thank you @HLWeil. I updated git to   2.42, now it works.

**Comment by HLWeil** [comment]
Glad to hear it!

I opened an Issue in the Knowledgebase so this information will also find its way there.
