### ISSUE TITLE
[BUG] Assay identifier is not added to isa.investigation file

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/arcCommander#234]
**Describe the bug**
When registering an assay, there is no assay identifier row in all three isa.xlsx files.

**To Reproduce**
Initiate an ARC, add a study with an assay (arc a add -s MyStudy -a MyAssay)

**Expected behavior**
A row with the assay identifier similar to study identifier.

**OS and framework information (please complete the following information):**
macOS
arc commander v0.5.0 same for v1.0.0 (preview2)

**Comment by HLWeil** [comment]
Hey @andreaschrader,

this is because this field does neither exist in ISA Tab nor ISA Json (which is a shame). Having the `Identifier` as a argument is just for user convenience. 

Feel free to add your perspective in https://github.com/nfdi4plants/ARC-specification/issues/74.
