### ISSUE TITLE
[Feature Request] name of binaries

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#238]
Regarding https://github.com/nfdi4plants/ARCCommander/releases/tag/v1.0.0

There's an issue with the names of the binaries / executables: `arc_<OS>`. All docs are written for `arc ...`. 

Option 1: The way it was before, having one release per OS.

Option 2: We adapt the installation, so that `arc_<OS>` is moved and added to $PATH as `arc`

Option 3: Only rename the windows executable to arc.exe, since on Linux and macOS we need to install "by hand" anyways (and follow option 2 there)

**Comment by HLWeil** [comment]
Thanks for the input, I agree that we need some sort of solution. 

I'm really not a friend of `Option 1`. That's why I did the change. It clutteres the release history a lot. And the whole `latest` thing is kinda broken.

With `Option 2` you mean having a rename step in the installation guide?

**Comment by Brilator** [comment]
> With `Option 2` you mean having a rename step in the installation guide?

Yes. See PR linked above.

**Comment by HLWeil** [comment]
I'd say go. With the ARCitect taking the role as the community tool, the ARCCommander is becoming a niche tool for enthusiasts. They will probably manage a rename

**Comment by Brilator** [comment]
Alright. Would it still be easily automated to call the win thing arc.exe? 
So the windows people would still have the convenience of click-downloading (balanced with the inconvenience of adding to PATH)

**Comment by HLWeil** [comment]
Technically this would be a no-brainer, but it feels like a disturbance in the force _(of order)_.

**Comment by HLWeil** [comment]
Done.
