### ISSUE TITLE
ArcCommander should write into AssayMetaData

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander#35]
At the moment the `AssayMetaData` sheet gets created by the arcCommander but it is not being written to or read from. This should be implemented

**Comment by HLWeil** [comment]
Functionality to make this happen added in 92de1c2fc0ae213fea4b07bb4126a8358d738208

**Comment by omaus** [comment]
Functionality added in https://github.com/nfdi4plants/arcCommander/commit/0570a56a4d7675f02a4c054f606e9bf6578afab3
