### ISSUE TITLE
Installation instruction (OsX) 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#42]
Until there is a fully clickable MacOS executable (disk image, .dmg), I would suggest to add something like the following to the installation instructions: 
1. Download the latest release
2. Open a Terminal (Applications -> Utilities -> Terminal)
3. Change to directory where you downloaded the arc e.g. `cd ~/Downloads/`
4. Change permissions to make arcCommander executable: `chmod a+x arc`
5. Move arc to a place you like e.g. `mv arc ~/Applications/`
6. Add that place to your bash_profile to make it executable via terminal from everywhere e.g. `echo 'export PATH="$HOME/Applications/:$PATH"' >> ~/.bash_profile`
7. Start a new terminal for this to take effect. 
8. Run arcCommander from the terminal by executing `arc`

---- 
MacOS security note: 
On first execution, MacOS will not allow arc to be run. Instead it opens a pop-up: 
> "arc" cannot be opened because it is from an unidentified developer

Open the Security Panel in system Preferences (Applications -> System Preferences -> "Security & Privacy") and click the bottom-right button "Allow Anyway" right next to 
> arc was blocked from use because it is not from an identified developer. 

Head back to the terminal and execute `arc` again. Another pop-up will ask you to confirm by clicking "Open".

**Comment by Brilator** [comment]
@omaus 
@muehlhaus

**Comment by Brilator** [comment]
Thanks for updating the README. 
Just a quick confirmation from the Mac side of life:

# Intall developer version on MacOS
Download ZIP from https://github.com/nfdi4plants/arcCommander.git

```
cd ~/Downloads/arcCommander-developer
chmod a+x ./build.sh
./build.sh

dotnet bin/ArcCommander/netcoreapp3.1/arc.dll

mv ~/Downloads/arcCommander-developer ~/Applications/
```

Add alias for developer arc to bash_profile (i.e. to prevent interfering with running version)

```
echo 'alias devarc="dotnet ~/Applications/arcCommander-developer/bin/ArcCommander/netcoreapp3.1/arc.dll"' >> ~/.bash_profile

mkdir ~/ARCtest
cd ~/ARCtest
devarc init
```

dotnet --version
> 3.1.402

**Comment by omaus** [comment]
@Brilator Nice! Do you want me to add this to the Readme? 😅

**Comment by Brilator** [comment]
No, thanks. This was more of a note to myself and whoever else might need it. But developers around here will likely know what to do anyways. 
Maybe we can hide it in the wiki at some point.

**Comment by Brilator** [comment]
Quick-and-dirty (incl. OS specific config)

```
cd ~/Downloads/
chmod a+x arc
mv arc ~/Applications/
echo 'export PATH="$HOME/Applications/:$PATH"' >> ~/.bash_profile
mkdir ~/.config/arccommander/; mv config ~/.config/arccommander/config
arc
open "x-apple.systempreferences:com.apple.preference.security"
```

**Comment by Brilator** [comment]
@HLWeil @omaus @muehlhaus 
MacOS Installation with config file works fine. Nano is ok and definitely a bit handier than vim. 
But do my perfectionist heart a favor and rename assay.isa.xlsx to isa.assay.xlsx in the config (and elsewhere) or is there a reason for this to persist?
