### ISSUE TITLE
[Wiki suggestions] Minor edits

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#45]
Since I cannot edit / comment / fork the wiki, I'll add some suggestions here that come to mind while testing arcCommander.

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/arcCommander/wiki/5.-Assay#51-addition-of-assays
Bullet 3: arc a register -> `arc a register`

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/arcCommander/wiki/3.-Investigation#32-registering-persons-to-investigation

Link to ontology fell out of last row in the table (RolesTermSourceREF). 
Also, isn't there a better link / handier representation of this ontology?https://sparontologies.github.io/scoro/current/scoro.xml

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/arcCommander/wiki/4.-Study#41-addition-of-studies
bullets 3 and 4: 
`arc s register`
`arc s add`

**Comment by HLWeil** [comment]
I gave you `maintain` rights so you should be able to edit the wiki now 👍

**Comment by Brilator** [comment]
Good idea. Thanks.
