### ISSUE TITLE
[BUG] `arc i create` does not open an editor, but command line arguments work 

### ISSUE THREAD

**Issue by HajiraJabeen** [nfdi4plants/arcCommander#53]
**Describe the bug**

In ubuntu, `arc i create` does not open an editor, and I get the error
"could not parse query: No such file or directory"

Whereas, `arc i create` with the arguments works 

**To Reproduce**
1. copy arc in ARC folder
2. > `arc init`
3. > `arc i create`

**Expected behaviour**
An editor should open as stated in 
https://github.com/nfdi4plants/arcCommander/wiki/3.-Investigation 

**OS and framework information (please complete the following information):**
 - OS: [Ubuntu 16.04]

**Additional context**
Add any other context about the problem here, like ideas for a solution.

**Comment by Brilator** [comment]
Same as on MacOS https://github.com/nfdi4plants/arcCommander/issues/43

**Comment by Brilator** [comment]
Tested on both Mac and linux (Ubuntu) with current version (0.3.1) and it works.
