### ISSUE TITLE
[Feature Request] Default Config

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander#73]
**Is your feature request related to a problem? Please describe.**
In system environments, storing and accessing config files might not be possible (e.g. when the user does not have rights)

**Describe the solution you'd like**
Loading the global config file could be a `try` function, possibly returning nothing. In this case the [getConfig](https://github.com/nfdi4plants/arcCommander/blob/8b40790e044c7153c28bd373219e07116bfd4c77/src/ArcCommander/ArcConfiguration.fs#L31) function could be enriched with every basic field needed for the ArcCommander to run, so there's always a file system independent fallback.

**Comment by HLWeil** [comment]
@omaus @JonasLukasczyk

**Comment by omaus** [comment]
>  In system environments, storing and accessing config files might not be possible (e.g. when the user does not have rights)

For system environments, it is afair not possible to *not* have rights in your own user directory for the OSs that .NET Core ships to.
But since this problem could emerge in specific virtual environments (most prominently Docker), I'll add a `try` functionality to it.

**Comment by omaus** [comment]
Done with 1f5d5460177bbc58df19859b22310a994c540a54
