### ISSUE TITLE
[Feature Request] Config file should be renamed

### ISSUE THREAD

**Issue by JonasLukasczyk** [nfdi4plants/arcCommander#74]
The ac creates and uses a file called `config`  in the default directory where config files should be located, which is `./config`. The name `config` is inappropriate since the name is to general. This directory contains other config files as well, and it is usual to name them according to the program they configure (e.g., `ParaView.config`). So I suggest to rename the file to `ArcCommander.config`.

**Comment by JonasLukasczyk** [comment]
If the path looks like this then it is fine. After extracting the arc binary from a container I got the error that no config file was found. So I put one named `config` directly in the `.config` folder and it worked. So I assumed the ac is programmed to look at `.config/config`.  Now it seems that this worked was just a coincidence. As long as the ac creates the subfolder everything is fine. If you can confirm this feel free to close the issue.

**Comment by omaus** [comment]
Done with 1f5d5460177bbc58df19859b22310a994c540a54
