### ISSUE TITLE
[Feature Request] Enable running external tools

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander#75]
**Is your feature request related to a problem? Please describe.**
Some tools like converters will be implemented by non .Net programmers. To enable seemless integration of these tools into the ArcCommander, a standardized approach for running compiled executables should be implemented.

**Describe the solution you'd like**
Commands unknown to the ArcCommander could be automatically handled by checking if an executable with the same name does exist in some specific executables folder.

**Comment by omaus** [comment]
> by checking if an executable with the same name does exist in some specific executables folder.

I think, PATH should also be looked at (and Linux-/Mac-equivalents).

**Comment by HLWeil** [comment]
Will close this now as the functionality was merged. Reopen, if improvements are required.
