### ISSUE TITLE
Add a config file

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander#8]
A config file could be added which stores some additional information for the ARC
This could e.g. be
- the standard editor used for querying arguments
- a default study to which all assays and computations are added per default
- github settings for syncing the arc.

This file could be created when initiating the ARC receiving its info through command line arguments

**Comment by HLWeil** [comment]
@muehlhaus which filePath you think fits better?
 `.arc/globalParams.yml `
+ everything in one place
- for many other tools, this folder(.paket,.fake, ..) does contain only temporary information

` .config/globalParams.yml` 
+ this might be more intuitive as it follows the standard
- makes the arc base folder more crowded

**Comment by cgarth** [comment]
Chiming in: I would follow the Git model and use `.arc/` for all per-ARC config. Maybe one could even consider a single `.arc` file?

`.config` is only standardized (in XDG via XDG_CONFIG_HOME) for per-user configuration, and has discoverability issues.

**Comment by muehlhaus** [comment]
I agree with @cgarth. We definitely should stick to the .acr/ folder decision. It should also be a folder as more files will arrive there...

**Comment by HLWeil** [comment]
Alright, that was my first pick anyways 👍

**Comment by HLWeil** [comment]
A more sophisticated configuration implementation is available with #20.

I split the configuration in global (arcCommanderBinaries/config) and local (specificArc/.arc/config). Both in ini format.

A more detailed expanation is given in the PR.
