### ISSUE TITLE
[Feature Request] `arc delete`

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/arcCommander#89]
**Is your feature request related to a problem? Please describe.**
Users might initiate an ARC in a folder where they also have other files and folders. If they later decide to delete the ARC, they have to remove all ARC-related files and folders by hand which might be a bit tricky the larger the root folder was before. 

**Describe the solution you'd like**
An `arc delete` function would aid with this. It can be easily implemented since we always know about every possible folder and file in an ARC root.

**Describe alternatives you've considered**
Let the users still delete ARC-stuff manually.

**Additional context**
A functionality with such consequences will be located in the Danger Zone, thus there should be a query if the action shall really be performed or not (typically, a y/n scenario).

**Comment by HLWeil** [comment]
Hey, like you stated, this functionality is actually a slippery sloap due to the dangers it presents. IMO the alternative way you described has been sufficient for now. 
I'll close this issue for now. Feel free to reopen if a need for this arises in the user community.
