### ISSUE TITLE
[BUG] Minor typo in error message during arc s remove

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#93]
**Describe the bug**
There's a word missing in the error message: 
`ERROR: Study with the identifier <to be deleted s id> does not in the investigation file.`

**To Reproduce**
1. Try to remove a study with `arc s remove -s` for which the study ID does not exist. 

**Expected behavior**
Should be "...does not exist in the investigation file"?

**Comment by omaus** [comment]
You, Sir, are totally correct. Will fix it asap.
