### ISSUE TITLE
[BUG] Prompt re-registration for assay when linked study is removed 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#94]
**Is your feature request related to a problem? Please describe.**
When removing a study (`arc s remove -s`) the linked assay is properly unregistered from the isa.investigation file, but not removed from the ARC (for good reason). However, it's then flying around unlinked (to study and inv) and also doesn't appear in `arc a list`.

**Describe the solution you'd like**
a) When removing studies throw a warning that an assay is linked
b) Suggest alternative studies to link the assay to (if exists), e.g. via message `arc a register -s <existing s id> -a`

**Comment by Brilator** [comment]
Would it also makes sense to let `arc a list` / `arc s list` display unregistered assays / studies, in case people just copy-dump them in there? Or is this part of validation during `arc update`?

**Comment by HLWeil** [comment]
Hey @Brilator, I think your a),b) suggestions for the initial problem would be the best way to assist the user. 

Also showing `unregistered` `assays` and `studies` when using `list` seems also sensible.

Thanks for your input

**Comment by HLWeil** [comment]
Proposed solution for the first problem: 

![image](https://user-images.githubusercontent.com/17880410/151780774-e6afcc91-457d-41dc-8c75-2ee8c2d0cdb5.png)
