### ISSUE TITLE
[BUG] minor: arc sync default commit message 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCCommander#97]
**Is your feature request related to a problem? Please describe.**
The default commit message during `arc sync` is "Update", which is very different from what `arc update` does. 

**Describe the solution you'd like**
Maybe exchange for a somewhat more informative commit message like "sync changes via arcCommander".

**Comment by omaus** [comment]
The idea behind this was that it says that the ARC was updated. But you are correct, it can be mistaken.
Your idea sounds quite good.

**Comment by Brilator** [comment]
maybe default add a `date` Wed Jun 14 13:58:43 CEST 2023 as well? 
Could make finding commits easier. 
#196

**Comment by HLWeil** [comment]
Well, the commits all do have a date anyways, so I don't really see much gain from this.
